// Package mpeg4audio decodes MPEG-4 AudioSpecificConfig (ISO/IEC 14496-3 §1.6.2.1),
// ADTS-shared rate/channel tables, and frame walks for implicit SBR/PS.
//
// [ParseConfig] reads declared geometry through hierarchical SBR/PS and the AAC-LC
// extension tail; it stops at unreadable fields (PCE, extensionFlag3, unknown AOT).
//
// [ParseRawDataBlock] and [ParseSBRSingleChannel] probe frames when config is silent.
// Walks succeed only by landing on syntax element boundaries.
//
// Tables are generated by gentables (not checked in):
//
//	cd gentables && go run . -spec /path/to/iso14496-3-2009.pdf -out ..
package mpeg4audio

// sampleRates maps samplingFrequencyIndex to Hz (not 13, 14, or 15 escape).
var sampleRates = [13]int{
	96000, 88200, 64000, 48000, 44100, 32000, 24000, 22050,
	16000, 12000, 11025, 8000, 7350,
}

// channelCounts maps channelConfiguration to count. 0=PCE; 8-10,15 reserved; 11-14 Amd.4 layouts.
var channelCounts = [16]int{0, 1, 2, 3, 4, 5, 6, 8, 0, 0, 0, 7, 8, 24, 8, 0}

// SampleRate maps index to Hz; 0 for reserved, escape (15), or out of range.
func SampleRate(index int) int {
	if index < 0 || index >= len(sampleRates) {
		return 0
	}
	return sampleRates[index]
}

// ChannelCount maps configuration to count; 0 for PCE or reserved.
func ChannelCount(config int) int {
	if config < 0 || config >= len(channelCounts) {
		return 0
	}
	return channelCounts[config]
}

// ObjectTypeName names AOT for display; unknown types return "AAC".
func ObjectTypeName(aot int) string {
	switch aot {
	case 1:
		return "AAC Main"
	case 2:
		return "AAC LC"
	case 3:
		return "AAC SSR"
	case 4:
		return "AAC LTP"
	case 23:
		return "AAC LD"
	case 39:
		return "AAC ELD"
	case 42:
		return "xHE-AAC"
	}
	return "AAC"
}

// Config is decoded AudioSpecificConfig geometry.
//
// SampleRate/Channels are core coder values. Output* are played geometry.
// SBRSignalled distinguishes explicit SBR denial from silence (truncated tail = silent).
type Config struct {
	ObjectType    int  // core audio object type, after any SBR or PS wrapper (2 = AAC LC)
	SampleRate    int  // core sample rate in Hz, 0 when the index is reserved
	ChannelConfig int  // the 4-bit channelConfiguration; 0 = the layout is in a program config element
	Channels      int  // ChannelCount(ChannelConfig)
	SBRSignalled  bool // the config states SBR presence either way, whether declared or denied
	SBR           bool // SBR is present
	PS            bool // parametric stereo is present
	ExtensionRate int  // extensionSamplingFrequency when SBR is present, else 0
}

// OutputSampleRate is extension rate when SBR declares one, else core rate.
func (c Config) OutputSampleRate() int {
	if c.SBR && c.ExtensionRate > 0 {
		return c.ExtensionRate
	}
	return c.SampleRate
}

// OutputChannels is 2 when PS over mono core, else core channels.
func (c Config) OutputChannels() int {
	if c.PS && c.ChannelConfig == 1 {
		return 2
	}
	return c.Channels
}

// ProfileName prefers HE-AAC/v2 spelling over core AOT.
func (c Config) ProfileName() string {
	switch {
	case c.SBR && c.PS:
		return "HE-AAC v2"
	case c.SBR:
		return "HE-AAC"
	}
	return ObjectTypeName(c.ObjectType)
}

// Sync extension types that can open the backward-compatible tail: 0x2B7
// introduces the SBR (and, nested, PS) signalling, 0x548 the PS flag inside it.
const (
	syncExtensionSBR = 0x2B7
	syncExtensionPS  = 0x548
)

// explicitRateIndex is the samplingFrequencyIndex that escapes to a 24-bit rate.
const explicitRateIndex = 15

// maxSampleRate caps explicit rate (655350 Hz = FLAC header max); above reads as 0.
const maxSampleRate = 655350

// ParseConfig decodes AudioSpecificConfig. ok=false only if b is too short for header.
func ParseConfig(b []byte) (Config, bool) {
	r := &bitReader{b: b}
	var c Config

	aot, ok := readObjectType(r)
	if !ok {
		return Config{}, false
	}
	rate, ok := readRate(r)
	if !ok {
		return Config{}, false
	}
	chanCfg, ok := r.read(4)
	if !ok {
		return Config{}, false
	}
	c.ObjectType, c.SampleRate, c.ChannelConfig = aot, rate, chanCfg
	c.Channels = ChannelCount(chanCfg)

	// Hierarchical signalling: AOT 5 (SBR) and 29 (PS) wrap the core object type,
	// which follows the extension rate.
	if aot == 5 || aot == 29 {
		c.SBRSignalled, c.SBR, c.PS = true, true, aot == 29
		extRate, ok := readRate(r)
		if !ok {
			return c.finish(), true
		}
		c.ExtensionRate = extRate
		core, ok := readObjectType(r)
		if !ok {
			return c.finish(), true
		}
		if core == 5 || core == 29 {
			// Nested SBR wrapper: drop extension rate.
			c.ExtensionRate = 0
			return c.finish(), true
		}
		c.ObjectType = core
		if core == 22 {
			if _, ok := r.read(4); !ok { // extensionChannelConfiguration
				return c.finish(), true
			}
		}
		aot = core
	}

	// Only GA types (1-4,6,7) have a walkable specific config to the extension tail.
	switch aot {
	case 1, 2, 3, 4, 6, 7:
		if !parseGASpecificConfig(r, c.ChannelConfig, aot) {
			return c.finish(), true
		}
	default:
		return c.finish(), true
	}

	// Extension tail at current bit position only (no sync scan).
	if c.SBRSignalled || r.remaining() < 16 {
		return c.finish(), true
	}
	sync, _ := r.read(11)
	if sync != syncExtensionSBR {
		return c.finish(), true
	}
	extType, ok := readObjectType(r)
	if !ok {
		return c.finish(), true
	}
	switch extType {
	case 5:
		// SBRSignalled only after flag read; truncated tail stays silent, not denial.
		sbr, ok := r.read(1)
		if !ok {
			return c.finish(), true
		}
		c.SBRSignalled = true
		if sbr == 0 {
			return c.finish(), true
		}
		c.SBR = true
		if extRate, ok := readRate(r); ok {
			c.ExtensionRate = extRate
		}
		if r.remaining() < 12 {
			return c.finish(), true
		}
		if sync, _ := r.read(11); sync == syncExtensionPS {
			if ps, ok := r.read(1); ok && ps == 1 {
				c.PS = true
			}
		}
	case 22:
		sbr, ok := r.read(1)
		if !ok {
			return c.finish(), true
		}
		c.SBRSignalled = true
		if sbr == 1 {
			c.SBR = true
			if extRate, ok := readRate(r); ok {
				c.ExtensionRate = extRate
			}
		}
		r.read(4) // extensionChannelConfiguration
	}
	return c.finish(), true
}

func (c Config) finish() Config {
	// PS only valid over mono core.
	if c.PS && c.ChannelConfig != 1 {
		c.PS = false
	}
	return c
}

// readObjectType reads an audioObjectType: 5 bits, with 31 escaping to 6 more bits
// biased by 32.
func readObjectType(r *bitReader) (int, bool) {
	aot, ok := r.read(5)
	if !ok {
		return 0, false
	}
	if aot != 31 {
		return aot, true
	}
	ext, ok := r.read(6)
	if !ok {
		return 0, false
	}
	return ext + 32, true
}

// readRate reads a samplingFrequencyIndex and resolves it to Hz: a table lookup,
// or the 24-bit rate index 15 escapes to. A reserved index yields 0, which callers
// read as "the config declares no rate here"; ok is false only on a short read.
func readRate(r *bitReader) (int, bool) {
	index, ok := r.read(4)
	if !ok {
		return 0, false
	}
	if index != explicitRateIndex {
		return SampleRate(index), true
	}
	rate, ok := r.read(24)
	if !ok {
		return 0, false
	}
	if rate > maxSampleRate {
		return 0, true
	}
	return rate, true
}

// parseGASpecificConfig walks GA specific config to extension tail. false if PCE or extensionFlag3.
func parseGASpecificConfig(r *bitReader, chanCfg, aot int) bool {
	if _, ok := r.read(1); !ok { // frameLengthFlag
		return false
	}
	dependsOnCoreCoder, ok := r.read(1)
	if !ok {
		return false
	}
	if dependsOnCoreCoder == 1 {
		if _, ok := r.read(14); !ok { // coreCoderDelay
			return false
		}
	}
	extensionFlag, ok := r.read(1)
	if !ok {
		return false
	}
	if chanCfg == 0 {
		return false // PCE follows
	}
	if aot == 6 {
		if _, ok := r.read(3); !ok { // layerNr
			return false
		}
	}
	if extensionFlag == 1 {
		extensionFlag3, ok := r.read(1)
		if !ok || extensionFlag3 == 1 {
			return false
		}
	}
	return true
}
