// Command gentables extracts the AAC and SBR Huffman codebooks and the scalefactor band
// offsets from the text of ISO/IEC 14496-3:2009 and writes them as Go source for package
// mpeg4audio. It is run by hand, not by go:generate: it needs a copy of the specification,
// which is not redistributable and is never checked in.
//
//	go run . -spec /path/to/iso14496-3-2009.pdf -out ..
//
// Every table is identified by its "Table 4.A.N" caption rather than its title text, since
// the extractor fragments titles but keeps the number intact. Each table is validated
// against the size the specification states for it, and a mismatch is a hard failure naming
// the table and the missing indices: a silently short codebook would decode garbage.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/ledongthuc/pdf"
)

func main() {
	spec := flag.String("spec", "", "path to the ISO/IEC 14496-3:2009 PDF")
	out := flag.String("out", ".", "directory to write the generated Go files into")
	flag.Parse()
	if *spec == "" {
		fail("-spec is required")
	}
	f, r, err := pdf.Open(*spec)
	if err != nil {
		fail("open %s: %v", *spec, err)
	}
	defer f.Close()

	aac, err := extractAAC(r)
	if err != nil {
		fail("%v", err)
	}
	sbr, err := extractSBR(r)
	if err != nil {
		fail("%v", err)
	}
	long, short, err := extractSWB(r)
	if err != nil {
		fail("%v", err)
	}

	write(filepath.Join(*out, "aac_tables.go"), renderAAC(aac))
	write(filepath.Join(*out, "sbr_tables.go"), renderSBR(sbr))
	write(filepath.Join(*out, "swb_tables.go"), renderSWB(long, short))
}

func fail(format string, a ...any) {
	fmt.Fprintf(os.Stderr, "gentables: "+format+"\n", a...)
	os.Exit(1)
}

const header = `// Code generated by gentables from ISO/IEC 14496-3:2009 Tables 4.A.1-4.A.12 (AAC),
// 4.A.79-4.A.88 (SBR) and 4.5.4 (scalefactor band offsets); DO NOT EDIT.

package mpeg4audio
`

func write(path, body string) {
	src, err := format.Source([]byte(body))
	if err != nil {
		fail("gofmt %s: %v", path, err)
	}
	if err := os.WriteFile(path, src, 0o644); err != nil {
		fail("write %s: %v", path, err)
	}
	fmt.Printf("wrote %s (%d bytes)\n", path, len(src))
}

// code is one Huffman codeword: its bit length and its value.
type code struct {
	length int
	value  uint32
}

// book accumulates one codebook's entries by symbol index, so a duplicate index is rejected
// and a missing one is reported by number.
type book struct {
	want    int
	entries map[int]code
}

func newBook(want int) *book { return &book{want: want, entries: map[int]code{}} }

// add records one entry, ignoring anything outside the table's declared size or already
// seen: the page furniture (headers, the licence footer, column captions) yields token
// triples that must not become codewords, and the size bound is what rejects them.
func (b *book) add(index, length int, value uint32) bool {
	if index < 0 || index >= b.want || length < 1 || length > 32 {
		return false
	}
	if length < 32 && value >= 1<<uint(length) {
		return false
	}
	if _, dup := b.entries[index]; dup {
		return false
	}
	b.entries[index] = code{length, value}
	return true
}

// finish returns the entries in symbol order, or an error naming what is missing.
func (b *book) finish(name string) ([]code, error) {
	if len(b.entries) != b.want {
		var missing []int
		for i := 0; i < b.want && len(missing) < 12; i++ {
			if _, ok := b.entries[i]; !ok {
				missing = append(missing, i)
			}
		}
		return nil, fmt.Errorf("%s: %d of %d entries extracted; missing %v", name, len(b.entries), b.want, missing)
	}
	out := make([]code, b.want)
	for i, c := range b.entries {
		out[i] = c
	}
	return out, nil
}

// rowWords returns each row of a page as its words, in reading order.
func rowWords(r *pdf.Reader, page int) ([][]string, error) {
	p := r.Page(page)
	if p.V.IsNull() {
		return nil, fmt.Errorf("page %d is missing", page)
	}
	rows, err := p.GetTextByRow()
	if err != nil {
		return nil, fmt.Errorf("page %d: %w", page, err)
	}
	out := make([][]string, 0, len(rows))
	for _, row := range rows {
		words := make([]string, 0, len(row.Content))
		for _, w := range row.Content {
			words = append(words, w.S)
		}
		out = append(out, words)
	}
	return out, nil
}

var tableCaption = regexp.MustCompile(`Table 4\.A\.(\d+)`)

// captionNumber returns the annex table number a row introduces, or -1. The words of a
// title fragment ("t_hu", "ffma", "n"), so the number is the only reliable identifier.
func captionNumber(spaced string) int {
	m := tableCaption.FindStringSubmatch(spaced)
	if m == nil {
		return -1
	}
	n, err := strconv.Atoi(m[1])
	if err != nil {
		return -1
	}
	return n
}

// aacSizes gives the entry count of each AAC annex table by its number: 4.A.1 is the
// scalefactor codebook, 4.A.2 through 4.A.12 are spectrum codebooks 1 through 11.
var aacSizes = map[int]int{
	1: 121, 2: 81, 3: 81, 4: 81, 5: 81, 6: 81, 7: 81, 8: 64, 9: 64, 10: 169, 11: 169, 12: 289,
}

func extractAAC(r *pdf.Reader) (map[int][]code, error) {
	books := map[int]*book{}
	for n, size := range aacSizes {
		books[n] = newBook(size)
	}
	cur := -1
	cursors := map[int]*columns{}
	for n, size := range aacSizes {
		cursors[n] = &columns{left: 0, right: (size + 1) / 2}
	}
	for page := 756; page <= 769; page++ {
		rows, err := rowWords(r, page)
		if err != nil {
			return nil, err
		}
		for _, words := range rows {
			if n := captionNumber(strings.Join(words, " ")); n >= 0 {
				cur = n
				continue
			}
			b, ok := books[cur]
			if !ok {
				continue
			}
			addAACRow(b, cursors[cur], strings.Join(words, ""))
		}
	}
	return finishAll(books, func(n int) string { return fmt.Sprintf("Table 4.A.%d", n) })
}

// columns tracks the next symbol expected in each of a codebook table's two printed
// columns. The left column starts at 0 and the right at the midpoint, and each data row
// carries one entry from each.
type columns struct{ left, right int }

// addAACRow reads one data row of an AAC codebook table. The extractor gives every word of
// a row the same X, so a column boundary is only visible where the text itself carries a
// space: a row reads as "8 19 7ffee698 f9", in which the codeword, the next index and its
// length have run together. The row is therefore parsed against what the table says must
// come next - the two expected symbol numbers - with whitespace treated as a boundary that
// must fall between cells and every other boundary left free. A row that does not parse
// (page furniture, a column heading) leaves the cursors alone.
func addAACRow(b *book, c *columns, row string) {
	left, right := strconv.Itoa(c.left), strconv.Itoa(c.right)
	if got, ok := matchCells(row, []string{left, right}); ok {
		b.add(c.left, got[0].length, got[0].value)
		b.add(c.right, got[1].length, got[1].value)
		c.left++
		c.right++
		return
	}
	// A column can run out one row before the other when the entry count is odd.
	if got, ok := matchCells(row, []string{left}); ok && c.left < (b.want+1)/2 {
		b.add(c.left, got[0].length, got[0].value)
		c.left++
		return
	}
	if got, ok := matchCells(row, []string{right}); ok && c.right < b.want {
		b.add(c.right, got[0].length, got[0].value)
		c.right++
	}
}

// matchCells parses row as one (index, length, codeword) group per expected index, in
// order, and reports whether the whole row is consumed. Each cell is a run of characters
// containing no whitespace; a whitespace character in row must fall between cells.
func matchCells(row string, indices []string) ([]code, bool) {
	out := make([]code, 0, len(indices))
	if !matchFrom(row, 0, indices, &out) {
		return nil, false
	}
	return out, true
}

func matchFrom(s string, pos int, indices []string, out *[]code) bool {
	pos = skipSpace(s, pos)
	if len(indices) == 0 {
		return skipSpace(s, pos) == len(s)
	}
	idx := indices[0]
	if !strings.HasPrefix(s[pos:], idx) {
		return false
	}
	p := skipSpace(s, pos+len(idx))
	// The length is one or two decimal digits; the codeword is up to eight hex digits and
	// must fit in that many bits. Both are tried longest-first, so the common unambiguous
	// reading is found without backtracking.
	for n := 2; n >= 1; n-- {
		if p+n > len(s) {
			continue
		}
		length, err := strconv.Atoi(s[p : p+n])
		if err != nil || length < 1 || length > 32 {
			continue
		}
		q := skipSpace(s, p+n)
		for m := min(8, len(s)-q); m >= 1; m-- {
			value, err := strconv.ParseUint(s[q:q+m], 16, 64)
			if err != nil || (length < 32 && value >= 1<<uint(length)) {
				continue
			}
			*out = append(*out, code{length, uint32(value)})
			if matchFrom(s, q+m, indices[1:], out) {
				return true
			}
			*out = (*out)[:len(*out)-1]
		}
	}
	return false
}

func skipSpace(s string, pos int) int {
	for pos < len(s) && (s[pos] == ' ' || s[pos] == '\t') {
		pos++
	}
	return pos
}

// sbrTables maps each SBR annex table number to the Go variable it becomes and its entry
// count. The 3.0 dB books are half the size of their 1.5 dB siblings.
var sbrTables = []struct {
	number int
	name   string
	size   int
}{
	{79, "sbrTEnv15", 121},
	{80, "sbrFEnv15", 121},
	{81, "sbrTEnvBal15", 49},
	{82, "sbrFEnvBal15", 49},
	{83, "sbrTEnv30", 63},
	{84, "sbrFEnv30", 63},
	{85, "sbrTEnvBal30", 25},
	{86, "sbrFEnvBal30", 25},
	{87, "sbrTNoise30", 63},
	{88, "sbrTNoiseBal30", 25},
}

// sbrRow matches a whitespace-stripped SBR row: one or two (index, 8-hex length, 8-hex
// codeword) triples. The extractor splits inside these cells, so the row is read as one
// run of characters rather than as words.
var sbrRow = regexp.MustCompile(`^(\d+)0[xX]([0-9A-Fa-f]{8})0[xX]([0-9A-Fa-f]{8})(?:(\d+)0[xX]([0-9A-Fa-f]{8})0[xX]([0-9A-Fa-f]{8}))?$`)

func extractSBR(r *pdf.Reader) (map[int][]code, error) {
	books := map[int]*book{}
	names := map[int]string{}
	for _, t := range sbrTables {
		books[t.number] = newBook(t.size)
		names[t.number] = t.name
	}
	cur := -1
	for page := 826; page <= 835; page++ {
		rows, err := rowWords(r, page)
		if err != nil {
			return nil, err
		}
		for _, words := range rows {
			if n := captionNumber(strings.Join(words, " ")); n >= 0 {
				cur = n
				continue
			}
			b, ok := books[cur]
			if !ok {
				continue
			}
			addSBRRow(b, strings.Join(strings.Fields(strings.Join(words, "")), ""))
		}
	}
	return finishAll(books, func(n int) string { return fmt.Sprintf("Table 4.A.%d (%s)", n, names[n]) })
}

func addSBRRow(b *book, flat string) {
	m := sbrRow.FindStringSubmatch(flat)
	if m == nil {
		return
	}
	for _, g := range [][3]string{{m[1], m[2], m[3]}, {m[4], m[5], m[6]}} {
		if g[0] == "" {
			continue
		}
		index, err1 := strconv.Atoi(g[0])
		length, err2 := strconv.ParseUint(g[1], 16, 64)
		value, err3 := strconv.ParseUint(g[2], 16, 64)
		if err1 == nil && err2 == nil && err3 == nil {
			b.add(index, int(length), uint32(value))
		}
	}
}

func finishAll(books map[int]*book, name func(int) string) (map[int][]code, error) {
	out := map[int][]code{}
	numbers := make([]int, 0, len(books))
	for n := range books {
		numbers = append(numbers, n)
	}
	sort.Ints(numbers)
	for _, n := range numbers {
		entries, err := books[n].finish(name(n))
		if err != nil {
			return nil, err
		}
		out[n] = entries
	}
	return out, nil
}

// swbCounts are the scalefactor band counts per sampling-frequency index that the
// specification states in its window-sequence tables. The extracted tables are checked
// against them, so a misread row cannot pass as a shorter band layout.
var (
	swbCountsLong  = [13]int{41, 41, 47, 49, 49, 51, 47, 47, 43, 43, 43, 40, 40}
	swbCountsShort = [13]int{12, 12, 12, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15}
)

// swbRates maps a sampling rate in Hz to its samplingFrequencyIndex. 7350 shares 8000's
// band layout and is filled from it rather than read separately.
var swbRates = map[int]int{
	96000: 0, 88200: 1, 64000: 2, 48000: 3, 44100: 4, 32000: 5, 24000: 6,
	22050: 7, 16000: 8, 12000: 9, 11025: 10, 8000: 11, 7350: 12,
}

var (
	// The dash is written as an escape: the specification prints an en dash here, and a
	// literal one is invisible to a reader scanning for the odd character out - and to a
	// mechanical dash cleanup, which would silently make this pattern match nothing.
	swbCaption  = regexp.MustCompile(`Table 4\.1(?:29|3\d|4[01]) \x{2013} scalefactor bands`)
	fsRow       = regexp.MustCompile(`^fs\s*\[kHz\]\s+(\S.*)$`)
	numberTok   = regexp.MustCompile(`[0-9]+(?:\.[0-9]+)?`)
	bracketed   = regexp.MustCompile(`\([^)]*\)`)
	numSwbRow   = regexp.MustCompile(`^num_swb_(long|short)_\s*window\s*(\d+)`)
	longKeyword = "LONG_WINDOW"
)

// swbTable is one extracted scalefactor band table: the rates it applies to and the band
// offsets, ending with the window length.
type swbTable struct {
	long    bool
	rates   []int
	numSwb  int
	offsets map[int]int
	last    int
}

func extractSWB(r *pdf.Reader) (long, short [13][]uint16, err error) {
	var tables []*swbTable
	var cur *swbTable
	for page := 601; page <= 607; page++ {
		rows, rerr := rowWords(r, page)
		if rerr != nil {
			return long, short, rerr
		}
		for _, words := range rows {
			line := strings.Join(strings.Fields(strings.Join(words, "")), " ")
			if swbCaption.MatchString(line) {
				cur = &swbTable{long: strings.Contains(line, longKeyword), offsets: map[int]int{}}
				tables = append(tables, cur)
				continue
			}
			if cur == nil {
				continue
			}
			if m := fsRow.FindStringSubmatch(line); m != nil {
				cur.rates = parseRates(m[1])
				continue
			}
			if m := numSwbRow.FindStringSubmatch(line); m != nil {
				cur.numSwb, _ = strconv.Atoi(m[2])
				continue
			}
			addSWBRow(cur, line)
		}
	}
	for _, t := range tables {
		if err := t.validate(); err != nil {
			return long, short, err
		}
		offsets := make([]uint16, t.numSwb+1)
		for i := 0; i < t.numSwb; i++ {
			offsets[i] = uint16(t.offsets[i])
		}
		offsets[t.numSwb] = uint16(t.last)
		for _, rate := range t.rates {
			idx, ok := swbRates[rate]
			if !ok {
				return long, short, fmt.Errorf("swb table names an unknown rate %d Hz", rate)
			}
			if t.long {
				long[idx] = offsets
			} else {
				short[idx] = offsets
			}
		}
	}
	// 7350 Hz shares the 8 kHz layout; the specification prints no separate table for it.
	long[12], short[12] = long[11], short[11]
	for i := range long {
		if len(long[i]) != swbCountsLong[i]+1 {
			return long, short, fmt.Errorf("swb long table for fs index %d has %d bands, want %d", i, len(long[i])-1, swbCountsLong[i])
		}
		if len(short[i]) != swbCountsShort[i]+1 {
			return long, short, fmt.Errorf("swb short table for fs index %d has %d bands, want %d", i, len(short[i])-1, swbCountsShort[i])
		}
	}
	return long, short, nil
}

// parseRates turns an "fs [kHz]" cell into rates in Hz. The cell separates its rates with
// commas, with the word "and", or with both ("32,44.1,48", "22.05 and 24").
func parseRates(s string) []int {
	var out []int
	for _, field := range numberTok.FindAllString(s, -1) {
		khz, err := strconv.ParseFloat(field, 64)
		if err != nil {
			continue
		}
		out = append(out, int(khz*1000+0.5))
	}
	return out
}

// addSWBRow reads the (band, offset) pairs of one two-column row. A trailing lone number is
// the window length that closes the table; the bracketed 1920-window alternates are dropped.
func addSWBRow(t *swbTable, line string) {
	tokens := strings.Fields(bracketed.ReplaceAllString(line, " "))
	for i := 0; i < len(tokens); {
		band, err1 := strconv.Atoi(tokens[i])
		if err1 != nil {
			i++
			continue
		}
		if i+1 < len(tokens) {
			offset, err2 := strconv.Atoi(tokens[i+1])
			if err2 == nil && band >= 0 && band < t.numSwb {
				if _, dup := t.offsets[band]; !dup {
					t.offsets[band] = offset
					i += 2
					continue
				}
			}
		}
		// Not a band index: the window length that terminates the table (1024 or 128), or
		// page furniture the size checks below reject.
		if band == 1024 || band == 128 {
			t.last = band
		}
		i++
	}
}

func (t *swbTable) validate() error {
	kind := "short"
	wantLast := 128
	if t.long {
		kind, wantLast = "long", 1024
	}
	if t.numSwb == 0 || len(t.rates) == 0 {
		return fmt.Errorf("swb %s table: num_swb %d, rates %v", kind, t.numSwb, t.rates)
	}
	if t.last != wantLast {
		return fmt.Errorf("swb %s table for %v ends at %d, want %d", kind, t.rates, t.last, wantLast)
	}
	prev := -1
	for i := 0; i < t.numSwb; i++ {
		v, ok := t.offsets[i]
		if !ok {
			return fmt.Errorf("swb %s table for %v is missing band %d of %d", kind, t.rates, i, t.numSwb)
		}
		if v <= prev && i > 0 {
			return fmt.Errorf("swb %s table for %v: band %d offset %d is not above %d", kind, t.rates, i, v, prev)
		}
		prev = v
	}
	if t.last <= prev {
		return fmt.Errorf("swb %s table for %v: terminator %d is not above the last band offset %d", kind, t.rates, t.last, prev)
	}
	return nil
}

func renderBook(b *bytes.Buffer, name string, entries []code) {
	fmt.Fprintf(b, "var %s = huffBook{\n", name)
	for _, c := range entries {
		fmt.Fprintf(b, "\t{Len: %d, Code: 0x%x},\n", c.length, c.value)
	}
	b.WriteString("}\n\n")
}

func renderAAC(books map[int][]code) string {
	var b bytes.Buffer
	b.WriteString(header)
	b.WriteString("\n// scalefactorBook is Table 4.A.1, the scalefactor delta codebook.\n")
	renderBook(&b, "scalefactorBook", books[1])
	b.WriteString("// spectrumBooks holds Tables 4.A.2 to 4.A.12, spectrum codebooks 1 to 11, indexed by\n" +
		"// codebook number. Index 0 is the ZERO codebook, which carries no spectral data and so\n" +
		"// has no table.\n")
	b.WriteString("var spectrumBooks = [12]huffBook{\n")
	for cb := 1; cb <= 11; cb++ {
		fmt.Fprintf(&b, "\t%d: spectrumBook%d,\n", cb, cb)
	}
	b.WriteString("}\n\n")
	for cb := 1; cb <= 11; cb++ {
		renderBook(&b, fmt.Sprintf("spectrumBook%d", cb), books[cb+1])
	}
	return b.String()
}

func renderSBR(books map[int][]code) string {
	var b bytes.Buffer
	b.WriteString(header)
	b.WriteString("\n// The SBR envelope and noise-floor codebooks, Tables 4.A.79 to 4.A.88, named after the\n" +
		"// specification's own table names.\n\n")
	for _, t := range sbrTables {
		renderBook(&b, t.name, books[t.number])
	}
	return b.String()
}

func renderSWB(long, short [13][]uint16) string {
	var b bytes.Buffer
	b.WriteString(header)
	b.WriteString("\n// swbOffsetLong and swbOffsetShort are the scalefactor band offsets for the 1024-sample\n" +
		"// long and 128-sample short windows, indexed by samplingFrequencyIndex. Each ends with\n" +
		"// the window length, so band n spans [offsets[n], offsets[n+1]).\n\n")
	renderOffsets(&b, "swbOffsetLong", long)
	renderOffsets(&b, "swbOffsetShort", short)
	return b.String()
}

func renderOffsets(b *bytes.Buffer, name string, tables [13][]uint16) {
	fmt.Fprintf(b, "var %s = [13][]uint16{\n", name)
	for i, t := range tables {
		parts := make([]string, len(t))
		for j, v := range t {
			parts[j] = strconv.Itoa(int(v))
		}
		fmt.Fprintf(b, "\t{%s},\n", strings.Join(parts, ", "))
		_ = i
	}
	b.WriteString("}\n\n")
}
